import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, ActivityIndicator, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { taxService, documentService } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';

export default function ExportReportScreen({ navigation }) {
  const { user } = useAuth();
  const { theme } = useTheme();
  const colors = theme.colors;
  const [loading, setLoading] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);
  const [taxData, setTaxData] = useState(null);

  useEffect(() => {
    loadTaxData();
  }, []);

  const loadTaxData = async () => {
    try {
      const response = await taxService.getTaxRecords();
      if (response.data.records?.length > 0) {
        setTaxData(response.data.records[response.data.records.length - 1]);
      }
    } catch (error) {
      console.log('Error loading tax data:', error);
    }
  };

  const formatCurrency = (amount) => {
    return '₹' + Math.round(amount || 0).toLocaleString('en-IN');
  };

  const generateTaxSummaryReport = () => {
    if (!taxData) {
      Alert.alert('No Data', 'Please calculate your tax first.');
      return null;
    }

    const currentYear = new Date().getFullYear();
    const report = `
==========================================
      TAXPILOT - TAX SUMMARY REPORT
      Financial Year: ${taxData.financial_year || `FY ${currentYear}-${currentYear + 1}`}
==========================================

GENERATED ON: ${new Date().toLocaleDateString('en-IN')}
TAXPAYER: ${user?.name || 'N/A'}
EMAIL: ${user?.email || 'N/A'}
PAN: ${user?.pan || 'N/A'}

------------------------------------------
INCOME DETAILS
------------------------------------------
Gross Income:        ${formatCurrency(taxData.gross_income)}
Total Deductions:    ${formatCurrency(taxData.total_deductions)}
Taxable Income:      ${formatCurrency(taxData.taxable_income)}
Total Income:        ${formatCurrency(taxData.total_income)}

------------------------------------------
TAX CALCULATION
------------------------------------------
Tax on Income:       ${formatCurrency(taxData.tax_on_income)}
Rebate 87A:          ${formatCurrency(taxData.rebate_87a)}
Tax After Rebate:     ${formatCurrency(taxData.tax_after_rebate)}
Cess (4%):           ${formatCurrency(taxData.cess)}
Health & Edu Cess:    ${formatCurrency(taxData.health_education_cess)}

==========================================
ESTIMATED TAX:       ${formatCurrency(taxData.estimated_tax)}
==========================================

------------------------------------------
IMPORTANT DATES
------------------------------------------
ITR Filing Due:      31st July ${currentYear}
Advance Tax Due:     15th of June, Sep, Dec, Mar

------------------------------------------
NOTE: This is a computer-generated report.
Please consult your CA for final filing.
==========================================

Generated by TaxPilot Pro
`;

    return report;
  };

  const generateInvestmentReport = async () => {
    try {
      const docsResponse = await documentService.getDocuments();
      const documents = docsResponse.data.documents || [];

      let report = `
==========================================
      TAXPILOT - INVESTMENT REPORT
      Financial Year: FY ${new Date().getFullYear()}-${new Date().getFullYear() + 1}
==========================================

GENERATED ON: ${new Date().toLocaleDateString('en-IN')}
TAXPAYER: ${user?.name || 'N/A'}
PAN: ${user?.pan || 'N/A'}

------------------------------------------
UPLOADED DOCUMENTS
------------------------------------------
`;

      if (documents.length === 0) {
        report += 'No documents uploaded yet.\n';
      } else {
        documents.forEach((doc, index) => {
          report += `
${index + 1}. ${doc.name}
   Type: ${doc.document_type || 'N/A'}
   Uploaded: ${doc.created_at ? new Date(doc.created_at).toLocaleDateString('en-IN') : 'N/A'}
`;
        });
      }

      report += `
------------------------------------------
SECTION WISE INVESTMENTS
------------------------------------------
Section 80C (Max 1,50,000):
  [ ] Life Insurance Premium
  [ ] PPF Contribution
  [ ] ELSS Mutual Funds
  [ ] NSC
  [ ] Tax Saving FD
  [ ] Home Loan Principal

Section 80D (Max 50,000):
  [ ] Health Insurance - Self
  [ ] Health Insurance - Parents

Section 80CCD(1B) (Max 50,000):
  [ ] NPS Contribution

==========================================
Generated by TaxPilot Pro
`;

      return report;
    } catch (error) {
      return null;
    }
  };

  const handleExport = async (reportType) => {
    setLoading(true);

    try {
      let reportContent = '';
      let fileName = '';

      switch (reportType) {
        case 'tax_summary':
          reportContent = generateTaxSummaryReport();
          fileName = `TaxSummary_${new Date().getFullYear()}.txt`;
          break;
        case 'investment':
          reportContent = await generateInvestmentReport();
          fileName = `InvestmentReport_${new Date().getFullYear()}.txt`;
          break;
        case 'full_report':
          const taxReport = generateTaxSummaryReport();
          const investReport = await generateInvestmentReport();
          reportContent = taxReport + '\n\n' + (investReport || '');
          fileName = `FullTaxReport_${new Date().getFullYear()}.txt`;
          break;
        default:
          reportContent = 'Report content';
          fileName = `Report_${Date.now()}.txt`;
      }

      if (!reportContent) {
        Alert.alert('Error', 'Failed to generate report');
        return;
      }

      if (Platform.OS === 'web') {
        Alert.alert('Success', 'Report generated! Copy the content from the generated file.', [
          { text: 'OK' },
        ]);
        setLoading(false);
        return;
      }

      const filePath = FileSystem.documentDirectory + fileName;
      await FileSystem.writeAsStringAsync(filePath, reportContent);

      const shareUri = Platform.OS === 'android' ? `file://${filePath}` : filePath;
      
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(shareUri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Tax Report',
        });
      } else {
        Alert.alert('Success', `Report saved as ${fileName}`, [
          { text: 'OK' },
        ]);
      }
    } catch (error) {
      Alert.alert('Error', 'Failed to export report: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  const reports = [
    {
      id: 'tax_summary',
      title: 'Tax Summary',
      description: 'Complete breakdown of your tax calculation with income, deductions, and tax liability',
      icon: 'document-text',
      color: '#3498db',
      hasData: !!taxData,
    },
    {
      id: 'investment',
      title: 'Investment Report',
      description: 'Summary of uploaded documents and section-wise investment checklist',
      icon: 'trending-up',
      color: '#27ae60',
      hasData: true,
    },
    {
      id: 'full_report',
      title: 'Complete Report',
      description: 'Full tax report including summary, investments, and recommendations',
      icon: 'folder',
      color: '#9b59b6',
      hasData: !!taxData,
    },
  ];

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Export Reports</Text>
        <Text style={styles.headerSubtitle}>Generate and share your tax documents</Text>
      </View>

      <ScrollView style={styles.content}>
        <View style={[styles.infoCard, { backgroundColor: colors.primary + '15' }]}>
          <Ionicons name="information-circle" size={24} color={colors.primary} />
          <View style={styles.infoContent}>
            <Text style={[styles.infoTitle, { color: colors.text }]}>PDF Reports</Text>
            <Text style={[styles.infoText, { color: colors.textSecondary }]}>
              Generate comprehensive tax reports to share with your CA or for your records.
            </Text>
          </View>
        </View>

        <View style={styles.reportsSection}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>Available Reports</Text>

          {reports.map((report) => (
            <TouchableOpacity
              key={report.id}
              style={[styles.reportCard, { backgroundColor: colors.card }, !report.hasData && styles.reportCardDisabled]}
              onPress={() => handleExport(report.id)}
              disabled={loading}
            >
              <View style={[styles.reportIcon, { backgroundColor: report.color + '20' }]}>
                <Ionicons name={report.icon} size={28} color={report.color} />
              </View>
              <View style={styles.reportInfo}>
                <Text style={[styles.reportTitle, { color: colors.text }]}>{report.title}</Text>
                <Text style={[styles.reportDesc, { color: colors.textSecondary }]}>{report.description}</Text>
                {!report.hasData && (
                  <View style={styles.noDataBadge}>
                    <Ionicons name="alert-circle" size={14} color={colors.warning} />
                    <Text style={[styles.noDataText, { color: colors.warning }]}>Calculate tax first</Text>
                  </View>
                )}
              </View>
              <Ionicons name="share-outline" size={24} color={colors.textSecondary} />
            </TouchableOpacity>
          ))}
        </View>

        <View style={styles.shareSection}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>Quick Share</Text>

          <View style={styles.shareButtons}>
            <TouchableOpacity style={styles.shareButton}>
              <View style={[styles.shareIcon, { backgroundColor: '#1877f2' }]}>
                <Ionicons name="mail" size={20} color="#fff" />
              </View>
              <Text style={[styles.shareText, { color: colors.textSecondary }]}>Email</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.shareButton}>
              <View style={[styles.shareIcon, { backgroundColor: '#25d366' }]}>
                <Ionicons name="logo-whatsapp" size={20} color="#fff" />
              </View>
              <Text style={[styles.shareText, { color: colors.textSecondary }]}>WhatsApp</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.shareButton}>
              <View style={[styles.shareIcon, { backgroundColor: '#1da1f2' }]}>
                <Ionicons name="cloud-upload" size={20} color="#fff" />
              </View>
              <Text style={[styles.shareText, { color: colors.textSecondary }]}>Cloud</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.shareButton}>
              <View style={[styles.shareIcon, { backgroundColor: '#ff0000' }]}>
                <Ionicons name="download" size={20} color="#fff" />
              </View>
              <Text style={[styles.shareText, { color: colors.textSecondary }]}>Save</Text>
            </TouchableOpacity>
          </View>
        </View>

        <View style={styles.tipsSection}>
          <Text style={[styles.sectionTitle, { color: colors.text }]}>Report Tips</Text>
          
          <View style={[styles.tipCard, { backgroundColor: colors.card }]}>
            <Ionicons name="calendar" size={24} color={colors.primary} />
            <View style={styles.tipContent}>
              <Text style={[styles.tipTitle, { color: colors.text }]}>Keep Records</Text>
              <Text style={[styles.tipText, { color: colors.textSecondary }]}>
                Download and save your tax reports annually for future reference and compliance.
              </Text>
            </View>
          </View>

          <View style={[styles.tipCard, { backgroundColor: colors.card }]}>
            <Ionicons name="people" size={24} color={colors.success} />
            <View style={styles.tipContent}>
              <Text style={[styles.tipTitle, { color: colors.text }]}>Share with CA</Text>
              <Text style={[styles.tipText, { color: colors.textSecondary }]}>
                Share your reports with your CA before the filing deadline for smoother ITR filing.
              </Text>
            </View>
          </View>

          <View style={[styles.tipCard, { backgroundColor: colors.card }]}>
            <Ionicons name="shield-checkmark" size={24} color="#9b59b6" />
            <View style={styles.tipContent}>
              <Text style={[styles.tipTitle, { color: colors.text }]}>Secure Storage</Text>
              <Text style={[styles.tipText, { color: colors.textSecondary }]}>
                Use password-protected sharing options for sensitive financial documents.
              </Text>
            </View>
          </View>
        </View>

        {loading && (
          <View style={[styles.loadingOverlay, { backgroundColor: colors.card + 'E6' }]}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={[styles.loadingText, { color: colors.text }]}>Generating Report...</Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    backgroundColor: '#2c3e50',
    padding: 20,
    paddingTop: 60,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#bdc3c7',
    marginTop: 5,
  },
  content: {
    flex: 1,
    padding: 15,
  },
  infoCard: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
  },
  infoContent: {
    flex: 1,
    marginLeft: 12,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  infoText: {
    fontSize: 14,
    marginTop: 4,
  },
  reportsSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  reportCardDisabled: {
    opacity: 0.7,
  },
  reportIcon: {
    width: 55,
    height: 55,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reportInfo: {
    flex: 1,
    marginLeft: 12,
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  reportDesc: {
    fontSize: 13,
    marginTop: 4,
  },
  noDataBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  noDataText: {
    fontSize: 12,
    marginLeft: 4,
  },
  shareSection: {
    marginBottom: 20,
  },
  shareButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  shareButton: {
    alignItems: 'center',
  },
  shareIcon: {
    width: 45,
    height: 45,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  shareText: {
    fontSize: 12,
  },
  tipsSection: {
    marginBottom: 30,
  },
  tipCard: {
    flexDirection: 'row',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  tipContent: {
    flex: 1,
    marginLeft: 12,
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  tipText: {
    fontSize: 14,
    marginTop: 4,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
  },
});
